//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSUCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerDBEntities : DbContext
    {
        public ComputerDBEntities()
            : base("name=ComputerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBComputer> DBComputer { get; set; }
        public virtual DbSet<DBCPU> DBCPU { get; set; }
        public virtual DbSet<DBGPU> DBGPU { get; set; }
    }
}
