//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSUCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBComputer
    {
        public int Id { get; set; }
        public string OwnerName { get; set; }
        public string Motherboard_Size { get; set; }
        public int GPU_Id { get; set; }
        public int CPU_Id { get; set; }
        public int RAM_Size { get; set; }
        public int Drive_Count { get; set; }
    
        public virtual DBCPU DBCPU { get; set; }
        public virtual DBGPU DBGPU { get; set; }
    }
}
